//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StalkerPDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacja
    {
        public int Id_relacji { get; set; }
        public int Id_frakcji_p { get; set; }
        public int Id_frakcji_d { get; set; }
        public string Rodzaj_relacji { get; set; }
    
        public virtual Frakcja Frakcja { get; set; }
        public virtual Frakcja Frakcja1 { get; set; }
    }
}
