//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StalkerPDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StalkerP4Entities : DbContext
    {
        public StalkerP4Entities()
            : base("name=StalkerP4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asortyment> Asortyment { get; set; }
        public virtual DbSet<Czlonkostwo> Czlonkostwo { get; set; }
        public virtual DbSet<Frakcja> Frakcja { get; set; }
        public virtual DbSet<Granica> Granica { get; set; }
        public virtual DbSet<Handlarz> Handlarz { get; set; }
        public virtual DbSet<Relacja> Relacja { get; set; }
        public virtual DbSet<Sprzedaz> Sprzedaz { get; set; }
        public virtual DbSet<Stalker> Stalker { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terytorium> Terytorium { get; set; }
        public virtual DbSet<Uklad> Uklad { get; set; }
    }
}
