//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StalkerPDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uklad
    {
        public int Id_ukladu { get; set; }
        public int Id_frakcji { get; set; }
        public int Id_handlarza { get; set; }
    
        public virtual Frakcja Frakcja { get; set; }
        public virtual Handlarz Handlarz { get; set; }
    }
}
